### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kothamasipradeep** [importRS/twittEmotion#2]
Hi Sir,this is Kothamasi Pradeep and Iam from Hyderabad.Iam working on your twitter sentiments so i took your project.The Frontend is working good but it's not fetching tweets when iam trying to search for a user or hashtag.It occuring an Type error:Nonetype is not iterable.Iam attaching the screenshots of the errors please go through it and help me to fix this issue .[
![Screenshot (2)](https://user-images.githubusercontent.com/94107146/141927411-59793d00-e247-4db3-9a23-4eabd3776bc9.png)
![Screenshot (3)](https://user-images.githubusercontent.com/94107146/141927420-b383b721-26ac-4aec-bc3d-ecc20cfc9a83.png)
](url)

**Comment by rajneeshXpandey** [comment]
Use your own Twitter API keys



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/16/21,
01:12:48 PM

**Comment by rajneeshXpandey** [comment]
Use your own Twitter API keys and follow README.md

**Comment by kothamasipradeep** [comment]
Iam using my own API keys Sir,but it still getting the same error.
